#!/usr/bin/env bash
#
# This setup script configures defautl settings for Mac OS X. The settings are
# found in the `defaults` folder and they are broken down by domain into several
# files. Please read and understand the files before blindly applying to your
# own computer.
#
# References
# * https://github.com/dstroot/.osx
# * https://github.com/mathiasbynens/dotfiles/blob/master/.macos
# * https://gist.github.com/garethrees/2470157
# * http://rixstep.com/2/20060901,00.shtml
# -----------------------------------------------------------------------------

COMPUTER_NAME="Vilya"
COMPUTER_UUID=`ioreg -rd1 -c IOPlatformExpertDevice | grep -E '(UUID)' | awk '{print $3}' | tr -d \"`

# easy access to documents in iCloud Drive
CLOUD_DOCS="${HOME}/Library/Mobile Documents/com~apple~CloudDocs"

RELATIVE_PATH="`dirname \"$0\"`"
ABSOLUTE_PATH=$(cd ${RELATIVE_PATH}; pwd)
source "${RELATIVE_PATH}/colors.sh"

DEFAULTS_PATH="${RELATIVE_PATH}/defaults"
declare -a DEFAULTS

# Output the program name
msg "Running: $0"

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# process all defaults
if [ $# -eq 0 ]; then
  DEFAULTS=${DEFAULTS_PATH}/*

# or process the specified defaults
else
  for file in $@; do
    DEFAULTS+=("${DEFAULTS_PATH}/$(basename $file)")
  done
fi

for file in ${DEFAULTS[@]}; do
  echo ""
  blue  "==================================================="
  white " Processing $(basename $file) configuration"
  blue  "==================================================="
  source $file
done

echo ""
green "All Done!"
red   "Note: some of these changes require a logout/restart to take effect."

exit 0

# vim:ft=sh
