#!/bin/bash
#/ Usage: strap
#/ Install development dependencies on macOS.
set -e

log()  { echo "--> $*"; }
logk() { echo "OK"; }

# Install Ansible.
if [ -z "$(command -v ansible)" ]; then
  log "Installing Ansible:"
  sudo easy_install pip
  pip install --upgrade setuptools --user python
  sudo pip install ansible --quiet
  logk
fi

# Install roles from Ansible Galaxy
log "Installing Ansible Galaxy roles:"
ansible-galaxy install -p "ansible/roles" -r "requirements.yml"
logk
